version: "3.9"  # Specify Docker Compose version

services:
  openwebui_cpu:
    image: openwebui_v4
    container_name: openwebui_v4_latest
    restart: always
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    networks:
      - open-webui

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - open-webui

volumes:
  open-webui:  # Volume for Open WebUI
  ollama:      # Volume for Ollama

networks:
  open-webui:
    driver: bridge